name: Run Basic Testes


# em que momento será executada
on: 
    pull_request:
      branches: [master]

jobs:
    # o que vai ser feito nessa pipeline
    # só teremos um job: rodar os testes
    cypress-run:
        # maquina que será executado
        runs-on: ubuntu-latest

        # passo a passo para rodar os testes
        steps:
            - name: Checkout/Clone do prjeto
              uses: actions/checkout@v4

            - name: Instalar dependências
              run: npm install

            - name: Rodar testes
              run: npx cypress run --record
              env: 
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            